import { defaultCache } from '@serwist/next/worker';
import type { PrecacheEntry, SerwistGlobalConfig } from 'serwist';
import { NetworkOnly, Serwist } from 'serwist';

// Extend the Service Worker global scope with the Serwist manifest injected at build time
declare global {
  interface WorkerGlobalScope extends SerwistGlobalConfig {
    __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
  }
}

declare const self: WorkerGlobalScope;

// Runtime caching rules that must run BEFORE defaultCache.
// defaultCache has a CacheFirst rule for *.mp4 and *.webm which would try to
// cache entire streaming video files — causing blank screens on S2 (MP4) streams.
// We intercept all video/HLS streaming requests and pass them straight to the network.
const streamingPassthrough = [
  // S2 MP4 streams served via the backend proxy
  {
    matcher: /\/api\/stream\//i,
    handler: new NetworkOnly(),
  },
  // HLS manifests and segments (any origin)
  {
    matcher: /\.(m3u8|ts)(\?.*)?$/i,
    handler: new NetworkOnly(),
  },
  // MP4/WebM video files fetched directly (e.g. S2 direct CDN links)
  {
    matcher: /\.(mp4|webm)(\?.*)?$/i,
    handler: new NetworkOnly(),
  },
];

const serwist = new Serwist({
  // Precaches all static JS/CSS/font chunks generated by Next.js at build time.
  // These are injected into __SW_MANIFEST by @serwist/next's webpack plugin.
  precacheEntries: self.__SW_MANIFEST,

  // Take control of all clients immediately — no waiting for a page reload
  skipWaiting: true,
  clientsClaim: true,

  // Navigate-fallback: if the user is offline and requests a page that isn't
  // in the precache, attempt to serve the root "/" from cache so the React app
  // still boots and can render whatever it can locally (e.g. /downloads).
  navigationPreload: false,
  fallbacks: {
    entries: [
      {
        url: '/',
        matcher({ request }) {
          return request.destination === 'document';
        },
      },
    ],
  },

  // Streaming passthrough rules run first, then defaultCache handles everything else.
  runtimeCaching: [...streamingPassthrough, ...defaultCache],
});

serwist.addEventListeners();
