import { defaultCache } from '@serwist/next/worker';
import type { PrecacheEntry, SerwistGlobalConfig } from 'serwist';
import { NetworkFirst, NetworkOnly, Serwist } from 'serwist';

// Extend the Service Worker global scope with the Serwist manifest injected at build time
declare global {
  interface WorkerGlobalScope extends SerwistGlobalConfig {
    __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
  }
}

declare const self: WorkerGlobalScope;

// Runtime caching rules that must run BEFORE defaultCache.
// defaultCache has a CacheFirst rule for *.mp4 and *.webm which would try to
// cache entire streaming video files — causing blank screens on S2 (MP4) streams.
// We intercept all video/HLS streaming requests and pass them straight to the network.
const streamingPassthrough = [
  // Local Electron proxy — must bypass SW entirely
  {
    matcher({ url }: { url: URL }) {
      return (
        url.hostname === '127.0.0.1' ||
        (url.hostname === 'localhost' && url.port !== '3000')
      );
    },
    handler: new NetworkOnly(),
  },
  // S2 MP4 streams served via the backend proxy
  {
    matcher: /\/api\/stream\//i,
    handler: new NetworkOnly(),
  },
  // Livestream API endpoints
  {
    matcher: /\/api\/livestream\//i,
    handler: new NetworkOnly(),
  },
  // HLS manifests and segments (any origin)
  {
    matcher: /\.(m3u8|ts)(\?.*)?$/i,
    handler: new NetworkOnly(),
  },
  // MP4/WebM video files fetched directly (e.g. S2 direct CDN links)
  {
    matcher: /\.(mp4|webm)(\?.*)?$/i,
    handler: new NetworkOnly(),
  },
];

// Pages: try network first, fall back to cache. This lets pages like
// /downloads work offline while always fetching fresh content when online.
const navigationRules = [
  {
    matcher({ request }: { request: Request }) {
      return request.destination === 'document';
    },
    handler: new NetworkFirst({
      cacheName: 'pages-html',
      networkTimeoutSeconds: 5,
    }),
  },
  {
    matcher({ request }: { request: Request }) {
      return request.headers.get('RSC') === '1';
    },
    handler: new NetworkFirst({
      cacheName: 'pages-rsc',
      networkTimeoutSeconds: 5,
    }),
  },
];

// Filter out the auto-discovered /public/offline entry — it's a broken URL
// generated by serwist scanning public/offline.html. The correct entry
// (/offline.html) is added via additionalPrecacheEntries in serwist.config.js.
const precacheEntries = self.__SW_MANIFEST?.filter(
  (entry) =>
    !(
      typeof entry === 'object' &&
      'url' in entry &&
      entry.url === '/public/offline'
    ),
);

const serwist = new Serwist({
  precacheEntries,
  skipWaiting: true,
  clientsClaim: true,
  navigationPreload: true,
  fallbacks: {
    entries: [
      {
        url: '/offline.html',
        matcher({ request }) {
          return request.destination === 'document';
        },
      },
    ],
  },
  runtimeCaching: [
    ...streamingPassthrough,
    ...navigationRules,
    ...defaultCache,
  ],
});

serwist.addEventListeners();
