import { defaultCache } from '@serwist/next/worker';
import type { PrecacheEntry, SerwistGlobalConfig } from 'serwist';
import { Serwist } from 'serwist';

// Extend the Service Worker global scope with the Serwist manifest injected at build time
declare global {
  interface WorkerGlobalScope extends SerwistGlobalConfig {
    __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
  }
}

declare const self: WorkerGlobalScope;

const serwist = new Serwist({
  // Precaches all static JS/CSS/font chunks generated by Next.js at build time.
  // These are injected into __SW_MANIFEST by @serwist/next's webpack plugin.
  precacheEntries: self.__SW_MANIFEST,

  // Take control of all clients immediately — no waiting for a page reload
  skipWaiting: true,
  clientsClaim: true,

  // Navigate-fallback: if the user is offline and requests a page that isn't
  // in the precache, attempt to serve the root "/" from cache so the React app
  // still boots and can render whatever it can locally (e.g. /downloads).
  navigationPreload: false,
  fallbacks: {
    entries: [
      {
        url: '/',
        matcher({ request }) {
          return request.destination === 'document';
        },
      },
    ],
  },

  // Runtime caching strategies for dynamic requests (API calls, images, etc.)
  runtimeCaching: defaultCache,
});

serwist.addEventListeners();
